### ISSUE TITLE
BBox API crashes LabView once the code is stopped

### ISSUE THREAD

**Issue by CT-FangTMY** [tmytek/bbox-one-api#2]
## Description
Hi Ethan,
Thanks for the help. We were able to run the code within the sounder code, but it crashes Labview once the code is stopped. We will be needing an end session block to avoid this problem. I hope this will also guarantee that we do not need to power cycle BBox each time we run the code.
Best Regards
Ozgur

Hi Tobias,
I  power cycle BBox. When I run the ConsoleApp1.exe it runs fine. Then as you see below init results is fine. But then the code exits with the following error. 
![image](https://user-images.githubusercontent.com/53503857/65652609-e839a280-e044-11e9-9607-987c81ca18b1.png)

## Steps to Reproduce
1. 
2. 
3. 
4. 

## Expected Behavior
We will be needing an end session block to avoid this problem. I hope this will also guarantee that we do not need to power cycle BBox each time we run the code.

## Current Behavior
Crash happens as described.

### Device ID
NCSU ones.

### BBox FW Version
v1.1.2

### BBox API Version
v1.2.2

### BBox Suite Version
N/A

**Comment by CT-FangTMY** [comment]
LabView does not close/deinit/clean .NET dll correctly when it is closed. Finding solutions.

**Comment by tobiashuang1985** [comment]
reconstruct the query IP process. Fixed the problem after api version v1.2.4
